export enum ECategories {
  MUSIC = 'music',
  ART = 'art',
  EATING = 'eating',
  TRAVEL = 'travel',
  GAMING = 'gaming',
  TECH = 'tech',
  EDUCATION = 'education',
  DANCE = 'dance',
  LIFESTYLE = 'lifestyle',
  ANIMATION = 'animation',
  DOCUMENTARY = 'documentary',
  WEB3 = 'web3',
  ANIMALS = 'animals',
}
